### ISSUE TITLE
Fails to compile under Xcode 15.0 Beta 6 

### ISSUE THREAD

**Issue by dbii** [liveview-native/liveview-native-swiftui-mapkit#202]
The error is `Sources/LiveViewNativeMapKit/MapContent/Marker.swift:87:44 Cannot convert value of type 'String' to expected argument type 'Text'` 

Apple docs now have two options which are identical except one has monogram as String and one as Text. 

```
init(LocalizedStringKey, monogram: String, coordinate: CLLocationCoordinate2D)
Creates a marker at the given location with the provided localized title and a monogram the map displays as the balloon's icon.
...
init(LocalizedStringKey, monogram: Text, coordinate: CLLocationCoordinate2D)
Creates a marker at the given location with the provided title key and monogram.
```

**Comment by bcardarella** [comment]
@dbii I'm going to close this as we're in 15.2 now. If you have other compilation issues please open a new issue.
