### ISSUE TITLE
could not install via ExactVersion or range

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/liveview-native-swiftui-mapkit#210]
I tagged both the swiftui client and this lib as "0.3.0-alpha.3" and when the mapkit lib couldn't install claiming it couldn't resolve the correct version for the swiftui lib. This lib has a version constraint for swiftui of `from: 0.2.0` which should allow everything up until `1.0.0`

I tried adding the tag `v0.3.0-alpha.3` to see if that would take but it didn't.

**Comment by carson-katri** [comment]
This seems to be working when using `0.3.0-alpha.3` of `liveview-client-swiftui` and `liveview-native-swiftui-mapkit`.

**Comment by bcardarella** [comment]
@carson-katri I suspect the problem is the cached git repo from the package manager on my machine. I'm going to try this to see if I can nuke the cache and confirm if it is working: https://github.com/brokenhandsio/swiftpm-cleanup

**Comment by bcardarella** [comment]
Closing as this appears to be an issue in SwiftPM and not on our end. We've temporarily resolved this by changing some installation range constraints https://github.com/apple/swift-package-manager/issues/7316
