### ISSUE TITLE
Error when adding local package: Package Resolution Failed

### ISSUE THREAD

**Issue by ryanwinchester** [liveview-native/liveview-native-swiftui-mapkit#211]
When adding this as a local package, I get a `Package Resolution Error`. This is odd since this same package (`SwiftSoup`) was included with the `liveview-client-swiftui` which succeeded.

<img width="1512" alt="Screenshot 2024-01-26 at 12 57 34 PM" src="https://github.com/liveview-native/liveview-native-swiftui-mapkit/assets/2897340/15cd531e-7015-4811-b644-364b353b39a0">

I was following the instructions for setting up [`boston_elixir`](https://github.com/DockYard/boston_elixir), cloning and adding as local packages.

<img width="1512" alt="Screenshot 2024-01-26 at 12 39 44 PM" src="https://github.com/liveview-native/liveview-native-swiftui-mapkit/assets/2897340/5a3a811d-fe76-4a5f-a50f-95147a0f0e4c">

### Specs
 * Mac Studio M2 Ultra
 * Sonoma 14.2.1
 * XCode 15.2
 * Deploy target iOS 17
 * Device iPhone 15 Pro

**Comment by carson-katri** [comment]
Could you try cleaning the project (Product > Clean Build Folder...) and adding the package again?

**Comment by bcardarella** [comment]
I'm still getting this error when installing mapkit dependency
<img width="734" alt="Screenshot 2024-01-31 at 9 38 28 AM" src="https://github.com/liveview-native/liveview-native-swiftui-mapkit/assets/18524/3788fa31-a1a3-40ef-854a-d2e1e3765567">

I have tried various methods for resetting the package cache without success.

**Comment by AZholtkevych** [comment]
Duplicates https://github.com/liveview-native/liveview-native-swiftui-mapkit/issues/210

**Comment by AZholtkevych** [comment]
Closing
